export const BOOKS = [
  {
    id: "b1_hasan_pilot",
    title: "Hasan Ingin Jadi Pilot",
    theme: "Cita-cita dan Karir",
    desc: "Buku karya Dr. Gusti Yarmi, Dr. Anggi Citra Apriliana, dan Imroa Hasna Berliana yang menceritakan impian Hasan untuk menjadi seorang pilot hebat.",
    cover: "https://i.ibb.co.com/jZhjvhcj/B1-HASAN-INGIN-JADI-PILOT-2-Page-01.jpg",
    illustration: "https://i.ibb.co.com/jZhjvhcj/B1-HASAN-INGIN-JADI-PILOT-2-Page-01.jpg",
    level: "Pembaca Awal B-1",
    grade: "Kelas 1",
    pages: [
      { text: "", image: "https://i.ibb.co.com/nMJSYXGT/B1-HASAN-INGIN-JADI-PILOT-2-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/vv1W05LN/B1-HASAN-INGIN-JADI-PILOT-2-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/pBsf1rcy/B1-HASAN-INGIN-JADI-PILOT-2-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/sJy2wxSz/B1-HASAN-INGIN-JADI-PILOT-2-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/DDm5rsmv/B1-HASAN-INGIN-JADI-PILOT-2-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/vxrzDFWs/B1-HASAN-INGIN-JADI-PILOT-2-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/G3QSMwWj/B1-HASAN-INGIN-JADI-PILOT-2-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/8gJgnrT2/B1-HASAN-INGIN-JADI-PILOT-2-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/d0D31ynB/B1-HASAN-INGIN-JADI-PILOT-2-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/Z1N90JY7/B1-HASAN-INGIN-JADI-PILOT-2-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/LXkwpCzh/B1-HASAN-INGIN-JADI-PILOT-2-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/04nQ24p/B1-HASAN-INGIN-JADI-PILOT-2-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/S76XfnfJ/B1-HASAN-INGIN-JADI-PILOT-2-Page-14.jpg" },
      { text: "", image: "https://i.ibb.co.com/qF2tft3D/B1-HASAN-INGIN-JADI-PILOT-2-Page-15.jpg" },
      { text: "", image: "https://i.ibb.co.com/20F1PNKh/B1-HASAN-INGIN-JADI-PILOT-2-Page-16.jpg" },
      { text: "", image: "https://i.ibb.co.com/dwPWnf6P/B1-HASAN-INGIN-JADI-PILOT-2-Page-17.jpg" },
      { text: "", image: "https://i.ibb.co.com/ymZHpywW/B1-HASAN-INGIN-JADI-PILOT-2-Page-18.jpg" }
    ]
  },
  {
    id: "b1_bersih_bersih_seru",
    title: "Bersih-Bersih Seru",
    theme: "SDG 3: Kehidupan Sehat dan Sejahtera",
    desc: "Buku fiksi seru karya Dr. Anggi Citra Apriliana yang mengajarkan tentang pentingnya menjaga kesehatan dan kebersihan bersama-sama.",
    cover: "https://i.ibb.co.com/cKtfhVMj/B1-BERSIH-BERSIH-SERU-Page-01.jpg",
    illustration: "https://i.ibb.co.com/cKtfhVMj/B1-BERSIH-BERSIH-SERU-Page-01.jpg",
    level: "Pembaca Awal B-1",
    grade: "Kelas 1",
    pages: [
      { text: "", image: "https://i.ibb.co.com/cc3WWCvJ/B1-BERSIH-BERSIH-SERU-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/RG0YBrmr/B1-BERSIH-BERSIH-SERU-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/fVC81qSj/B1-BERSIH-BERSIH-SERU-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/23zxYD9Q/B1-BERSIH-BERSIH-SERU-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/ynFqTXDG/B1-BERSIH-BERSIH-SERU-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/5xnsKhcf/B1-BERSIH-BERSIH-SERU-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/gZ87sp2W/B1-BERSIH-BERSIH-SERU-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/DfFmjxmm/B1-BERSIH-BERSIH-SERU-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/TqhRnqgK/B1-BERSIH-BERSIH-SERU-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/1Yt8HG7V/B1-BERSIH-BERSIH-SERU-Page-11.jpg" }
    ]
  },
  {
    id: "b2_petualangan_rara",
    title: "Petualangan Rara Mengelola Sampah",
    theme: "SDG 12: Konsumsi dan Produksi yang Bertanggung Jawab",
    desc: "Buku karya Dr. Anggi Citra Apriliana, M.Pd yang mengajak anak-anak berkenalan dengan cara seru mengelola sampah dan menjaga lingkungan kita tetap bersih.",
    cover: "https://i.ibb.co.com/LzwQVbTm/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-01.jpg",
    illustration: "https://i.ibb.co.com/LzwQVbTm/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-01.jpg",
    level: "Pembaca Awal B-2",
    grade: "Kelas 2",
    pages: [
      { text: "", image: "https://i.ibb.co.com/8gP35fhQ/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/TqcLfMQZ/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/TMJ18HzJ/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/yFMGkJFL/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/mFDz4FLy/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/Q329tvLX/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/JWZJKhLx/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/BK2LvyhG/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/PqsrXMF/B2-PETUALANGAN-RARA-MENGELOLA-SAMPAH-Page-10.jpg" }
    ]
  },
  {
    id: "b3_kreasi_hidroponik",
    title: "Berkreasi dengan Tanaman Hidroponik",
    theme: "SDG 2: Mengakhiri Kelaparan (Pertanian Berkelanjutan)",
    desc: "Buku inspiratif karya Dr. Anggi Citra Apriliana, M.Pd yang mengenalkan konsep bercocok tanam tanpa tanah untuk menghijaukan lingkungan di sekitar kita.",
    cover: "https://i.ibb.co.com/21hDMZDG/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-01.jpg",
    illustration: "https://i.ibb.co.com/21hDMZDG/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-01.jpg",
    level: "Pembaca Awal B-3",
    grade: "Kelas 3",
    pages: [
      { text: "", image: "https://i.ibb.co.com/cRwJTKP/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/4nNnPZ7P/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/q3S2Fgdb/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/4w8Ws2ZN/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/272Sn0xY/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/PZTJS2CT/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/8g09tb79/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/PkLSmrw/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/Wv7djZz3/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/6RWRTjR0/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/dJWYMpW0/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/fV5CVWCK/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/93hwpZXv/B3-BERKREASI-DENGAT-TANAMAN-HIDROPONIK-Page-14.jpg" }
    ]
  },
  {
    id: "b2_petualangan_kupu_kupu",
    title: "Petualangan di Hutan Kupu-Kupu",
    theme: "SDG 15: Ekosistem Daratan (Keanekaragaman Hayati)",
    desc: "Buku edukatif yang ditulis oleh Dr. Anggi Citra Apriliana, Dr. Gusti Yarmi, dan Nathania Ferina Lutfia ini mengajak kita mengikuti indahnya siklus dan petualangan kupu-kupu di alam bebas.",
    cover: "https://i.ibb.co.com/CLw29FD/B2-Petualangan-Kupu-Kupu-Page-01.jpg",
    illustration: "https://i.ibb.co.com/CLw29FD/B2-Petualangan-Kupu-Kupu-Page-01.jpg",
    level: "Pembaca Awal B-2",
    grade: "Kelas 2",
    pages: [
      { text: "", image: "https://i.ibb.co.com/1YYXgXLs/B2-Petualangan-Kupu-Kupu-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/xKZ756FB/B2-Petualangan-Kupu-Kupu-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/v6nhCkJP/B2-Petualangan-Kupu-Kupu-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/GvzQPLrJ/B2-Petualangan-Kupu-Kupu-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/Zzm9XLSD/B2-Petualangan-Kupu-Kupu-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/MyXBWC9c/B2-Petualangan-Kupu-Kupu-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/PZsGX1kG/B2-Petualangan-Kupu-Kupu-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/ZphBtWgK/B2-Petualangan-Kupu-Kupu-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/FkYT8XDb/B2-Petualangan-Kupu-Kupu-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/vC4PPd8B/B2-Petualangan-Kupu-Kupu-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/xphc6Fj/B2-Petualangan-Kupu-Kupu-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/JWQpX2sD/B2-Petualangan-Kupu-Kupu-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/gb4GBjmm/B2-Petualangan-Kupu-Kupu-Page-14.jpg" },
      { text: "", image: "https://i.ibb.co.com/DfYprR5d/B2-Petualangan-Kupu-Kupu-Page-15.jpg" },
      { text: "", image: "https://i.ibb.co.com/QFtWDPGx/B2-Petualangan-Kupu-Kupu-Page-16.jpg" },
      { text: "", image: "https://i.ibb.co.com/dJMkvvbf/B2-Petualangan-Kupu-Kupu-Page-17.jpg" },
      { text: "", image: "https://i.ibb.co.com/7Jt205mP/B2-Petualangan-Kupu-Kupu-Page-18.jpg" },
      { text: "", image: "https://i.ibb.co.com/kVRFF8dC/B2-Petualangan-Kupu-Kupu-Page-19.jpg" },
      { text: "", image: "https://i.ibb.co.com/1tWj0jW8/B2-Petualangan-Kupu-Kupu-Page-20.jpg" },
      { text: "", image: "https://i.ibb.co.com/SwPCLfKK/B2-Petualangan-Kupu-Kupu-Page-21.jpg" },
      { text: "", image: "https://i.ibb.co.com/ZpDPzmbh/B2-Petualangan-Kupu-Kupu-Page-22.jpg" },
      { text: "", image: "https://i.ibb.co.com/4zKxPDr/B2-Petualangan-Kupu-Kupu-Page-23.jpg" },
      { text: "", image: "https://i.ibb.co.com/cXDMJDQ9/B2-Petualangan-Kupu-Kupu-Page-24.jpg" },
      { text: "", image: "https://i.ibb.co.com/9kwmQNbf/B2-Petualangan-Kupu-Kupu-Page-25.jpg" },
      { text: "", image: "https://i.ibb.co.com/mr6cZcjn/B2-Petualangan-Kupu-Kupu-Page-26.jpg" }
    ]
  },
  {
    id: "b1_bela_si_kelinciku",
    title: "Bela Si Kelinciku",
    theme: "SDG 15: Ekosistem Daratan",
    desc: "Buku cerita lucu yang ditulis oleh Dr. Anggi Citra Apriliana, Dr. Gusti Yarmi, dan Shadrina Zahra Tambunan tentang merawat dan menyayangi binatang.",
    cover: "https://i.ibb.co.com/R4jGpQG9/B1-BELA-SI-KELINCIKU-Page-01.jpg",
    illustration: "https://i.ibb.co.com/R4jGpQG9/B1-BELA-SI-KELINCIKU-Page-01.jpg",
    level: "Pembaca Awal B-1",
    grade: "Kelas 1",
    pages: [
      { text: "", image: "https://i.ibb.co.com/gLK2G8Rg/B1-BELA-SI-KELINCIKU-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/B58CR4jb/B1-BELA-SI-KELINCIKU-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/zTRGXbSL/B1-BELA-SI-KELINCIKU-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/XxMhNwPd/B1-BELA-SI-KELINCIKU-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/hF5Jdjyw/B1-BELA-SI-KELINCIKU-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/sdBN2VQW/B1-BELA-SI-KELINCIKU-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/v4z1MvZS/B1-BELA-SI-KELINCIKU-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/23wCRSzm/B1-BELA-SI-KELINCIKU-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/qLnVJT0J/B1-BELA-SI-KELINCIKU-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/wNKntN4C/B1-BELA-SI-KELINCIKU-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/Zpsk3pFs/B1-BELA-SI-KELINCIKU-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/QjN461Qm/B1-BELA-SI-KELINCIKU-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/TDDs0HYL/B1-BELA-SI-KELINCIKU-Page-14.jpg" },
      { text: "", image: "https://i.ibb.co.com/pBjmb4LR/B1-BELA-SI-KELINCIKU-Page-15.jpg" },
      { text: "", image: "https://i.ibb.co.com/Df6Z6r3V/B1-BELA-SI-KELINCIKU-Page-16.jpg" },
      { text: "", image: "https://i.ibb.co.com/bg5c3Jnp/B1-BELA-SI-KELINCIKU-Page-17.jpg" },
      { text: "", image: "https://i.ibb.co.com/5XWtmgc9/B1-BELA-SI-KELINCIKU-Page-18.jpg" }
    ]
  },
  {
    id: "b1_jejak_di_padang_rumput",
    title: "Jejak di Padang Rumput",
    theme: "SDG 15: Ekosistem Daratan",
    desc: "Buku fiksi nan menarik karya Dr. Anggi Citra Apriliana, Dr. Gusti Yarmi, dan Siti Marselia Yasmin yang mengajak mengeksplorasi jejak seru satwa di alam terbuka.",
    cover: "https://i.ibb.co.com/cXC3GcPj/B1-JEJAK-DI-PADANG-RUMPUT-Page-01.jpg",
    illustration: "https://i.ibb.co.com/cXC3GcPj/B1-JEJAK-DI-PADANG-RUMPUT-Page-01.jpg",
    level: "Pembaca Awal B-1",
    grade: "Kelas 1",
    pages: [
      { text: "", image: "https://i.ibb.co.com/6RXDMmkB/B1-JEJAK-DI-PADANG-RUMPUT-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/twx4pBB8/B1-JEJAK-DI-PADANG-RUMPUT-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/CpNKQ2WC/B1-JEJAK-DI-PADANG-RUMPUT-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/v4z66B0z/B1-JEJAK-DI-PADANG-RUMPUT-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/1Y8jKCfG/B1-JEJAK-DI-PADANG-RUMPUT-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/xt2jhhh6/B1-JEJAK-DI-PADANG-RUMPUT-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/TD9pcVyD/B1-JEJAK-DI-PADANG-RUMPUT-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/VpSSYcm6/B1-JEJAK-DI-PADANG-RUMPUT-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/Xx6KD5Jb/B1-JEJAK-DI-PADANG-RUMPUT-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/mrQznZWX/B1-JEJAK-DI-PADANG-RUMPUT-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/3yh8d7ns/B1-JEJAK-DI-PADANG-RUMPUT-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/Fjs1XTJ/B1-JEJAK-DI-PADANG-RUMPUT-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/6cdH9jxS/B1-JEJAK-DI-PADANG-RUMPUT-Page-14.jpg" },
      { text: "", image: "https://i.ibb.co.com/mCF2tMvK/B1-JEJAK-DI-PADANG-RUMPUT-Page-15.jpg" },
      { text: "", image: "https://i.ibb.co.com/KzrWFfPS/B1-JEJAK-DI-PADANG-RUMPUT-Page-16.jpg" },
      { text: "", image: "https://i.ibb.co.com/cSpWDFpM/B1-JEJAK-DI-PADANG-RUMPUT-Page-17.jpg" },
      { text: "", image: "https://i.ibb.co.com/G313wXxN/B1-JEJAK-DI-PADANG-RUMPUT-Page-18.jpg" },
      { text: "", image: "https://i.ibb.co.com/rGVT8f1m/B1-JEJAK-DI-PADANG-RUMPUT-Page-19.jpg" }
    ]
  },
  {
    id: "b2_api_dan_pahlawan_kecil",
    title: "Api dan Pahlawan Kecil",
    theme: "SDG 15: Ekosistem Daratan",
    desc: "Buku edukatif karya Dr. Anggi Citra Apriliana, Dr. Gusti Yarmi, dan Hawa S Wulandari yang menceritakan tentang peran pahlawan ekosistem kecil dalam mengembalikan kehidupan akibat dampaknya kerusakan alam.",
    cover: "https://i.ibb.co.com/TB7xDJxF/B2-API-DAN-PAHLAWAN-KECIL-Page-01.jpg",
    illustration: "https://i.ibb.co.com/TB7xDJxF/B2-API-DAN-PAHLAWAN-KECIL-Page-01.jpg",
    level: "Pembaca Awal B-2",
    grade: "Kelas 2",
    pages: [
      { text: "", image: "https://i.ibb.co.com/Mx7dV09j/B2-API-DAN-PAHLAWAN-KECIL-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/S4VDLCkf/B2-API-DAN-PAHLAWAN-KECIL-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/9RGRYpK/B2-API-DAN-PAHLAWAN-KECIL-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/XrXBtYTH/B2-API-DAN-PAHLAWAN-KECIL-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/S1gMMRh/B2-API-DAN-PAHLAWAN-KECIL-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/Z6gfrbVb/B2-API-DAN-PAHLAWAN-KECIL-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/GvPdcWqM/B2-API-DAN-PAHLAWAN-KECIL-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/TD7gGHjy/B2-API-DAN-PAHLAWAN-KECIL-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/W4mhxjXw/B2-API-DAN-PAHLAWAN-KECIL-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/RGv9x9Nz/B2-API-DAN-PAHLAWAN-KECIL-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/3m6MQr5F/B2-API-DAN-PAHLAWAN-KECIL-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/vCQb7Ncs/B2-API-DAN-PAHLAWAN-KECIL-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/nsRDjDXp/B2-API-DAN-PAHLAWAN-KECIL-Page-14.jpg" },
      { text: "", image: "https://i.ibb.co.com/rfv5ss66/B2-API-DAN-PAHLAWAN-KECIL-Page-15.jpg" },
      { text: "", image: "https://i.ibb.co.com/27CdjN98/B2-API-DAN-PAHLAWAN-KECIL-Page-16.jpg" },
      { text: "", image: "https://i.ibb.co.com/cVSMmrS/B2-API-DAN-PAHLAWAN-KECIL-Page-17.jpg" }
    ]
  },
  {
    id: "b2_petualangan_lembah_awan",
    title: "Petualangan Lembah Awan",
    theme: "SDG 15: Ekosistem Daratan",
    desc: "Buku fiksi seru karya Dr. Gusti Yarmi, M.Pd, Dr. Anggi Citra Apriliana, M.Pd, dan Naila Izzati yang mengajak anak-anak mengeksplorasi keindahan lembah awan.",
    cover: "https://i.ibb.co.com/wFnVKVB7/B2-PETUALANGAN-LEMBAH-AWAN-Page-01.jpg",
    illustration: "https://i.ibb.co.com/wFnVKVB7/B2-PETUALANGAN-LEMBAH-AWAN-Page-01.jpg",
    level: "Pembaca Awal B-2",
    grade: "Kelas 2",
    pages: [
      { text: "", image: "https://i.ibb.co.com/1YXPbx5r/B2-PETUALANGAN-LEMBAH-AWAN-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/Fb2G3K1R/B2-PETUALANGAN-LEMBAH-AWAN-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/BVGdDx1X/B2-PETUALANGAN-LEMBAH-AWAN-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/ZRL01Mx7/B2-PETUALANGAN-LEMBAH-AWAN-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/TMjjQBcs/B2-PETUALANGAN-LEMBAH-AWAN-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/xtMNCkwX/B2-PETUALANGAN-LEMBAH-AWAN-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/xSbf24Wm/B2-PETUALANGAN-LEMBAH-AWAN-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/fdnsnwYh/B2-PETUALANGAN-LEMBAH-AWAN-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/jP20QkR8/B2-PETUALANGAN-LEMBAH-AWAN-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/Y4x74hV3/B2-PETUALANGAN-LEMBAH-AWAN-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/qYFcVjx6/B2-PETUALANGAN-LEMBAH-AWAN-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/B2y2D3hj/B2-PETUALANGAN-LEMBAH-AWAN-Page-13.jpg" },
      { text: "", image: "https://i.ibb.co.com/fVZjJWGm/B2-PETUALANGAN-LEMBAH-AWAN-Page-14.jpg" },
      { text: "", image: "https://i.ibb.co.com/BxPvzgm/B2-PETUALANGAN-LEMBAH-AWAN-Page-15.jpg" },
      { text: "", image: "https://i.ibb.co.com/4ZSLNzXQ/B2-PETUALANGAN-LEMBAH-AWAN-Page-16.jpg" },
      { text: "", image: "https://i.ibb.co.com/5xjJq7p0/B2-PETUALANGAN-LEMBAH-AWAN-Page-17.jpg" },
      { text: "", image: "https://i.ibb.co.com/Q3dz1wM6/B2-PETUALANGAN-LEMBAH-AWAN-Page-18.jpg" },
      { text: "", image: "https://i.ibb.co.com/gMb71nv2/B2-PETUALANGAN-LEMBAH-AWAN-Page-19.jpg" }
    ]
  },
  {
    id: "a_budi_lani",
    title: "Budi dan Lani Sahabat Sejati",
    theme: "Persahabatan",
    desc: "Buku karya Dr. Anggi Citra Apriliana, M. Pd, Dr. Gusti Yarmi, M. Pd, dan Siti Sabrina Zein yang menceritakan tentang indahnya persahabatan sejati antara Budi dan Lani.",
    cover: "https://i.ibb.co.com/35y7Cy6D/A-Budi-dan-Lani-Sahabat-Sejati-Page-01.jpg",
    illustration: "https://i.ibb.co.com/35y7Cy6D/A-Budi-dan-Lani-Sahabat-Sejati-Page-01.jpg",
    level: "Pembaca Dini A",
    grade: "PAUD/TK",
    pages: [
      { text: "", image: "https://i.ibb.co.com/LFkxsjB/A-Budi-dan-Lani-Sahabat-Sejati-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/yFL3md5D/A-Budi-dan-Lani-Sahabat-Sejati-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/gb1V2bTw/A-Budi-dan-Lani-Sahabat-Sejati-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/7Jsf2wtT/A-Budi-dan-Lani-Sahabat-Sejati-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/rf4SqrX2/A-Budi-dan-Lani-Sahabat-Sejati-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/WryzW8h/A-Budi-dan-Lani-Sahabat-Sejati-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/F4P9CmhC/A-Budi-dan-Lani-Sahabat-Sejati-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/HMkfH7W/A-Budi-dan-Lani-Sahabat-Sejati-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/DHvyxMhc/A-Budi-dan-Lani-Sahabat-Sejati-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/fV9TZdRf/A-Budi-dan-Lani-Sahabat-Sejati-Page-11.jpg" }
    ]
  },
  {
    id: "b2_nada_melodi",
    title: "Nada dan Melodinya",
    theme: "Seni dan Kreativitas",
    desc: "Buku karya Dr. Anggi Citra Apriliana, Dr. Gusti Yarmi, dan Khairani Salwa Anzani yang menceritakan tentang indahnya melodi dan musik dalam kehidupan Nada.",
    cover: "https://i.ibb.co.com/cSwspc8N/B2-Nada-dan-Melodinya-Page-01.jpg",
    illustration: "https://i.ibb.co.com/cSwspc8N/B2-Nada-dan-Melodinya-Page-01.jpg",
    level: "Pembaca Awal B-2",
    grade: "Kelas 2",
    pages: [
      { text: "", image: "https://i.ibb.co.com/9m3Qm5pZ/B2-Nada-dan-Melodinya-Page-02.jpg" },
      { text: "", image: "https://i.ibb.co.com/KxzCFCM8/B2-Nada-dan-Melodinya-Page-03.jpg" },
      { text: "", image: "https://i.ibb.co.com/mVtXHxdH/B2-Nada-dan-Melodinya-Page-04.jpg" },
      { text: "", image: "https://i.ibb.co.com/TD5d09Kp/B2-Nada-dan-Melodinya-Page-05.jpg" },
      { text: "", image: "https://i.ibb.co.com/1fMCRWKz/B2-Nada-dan-Melodinya-Page-06.jpg" },
      { text: "", image: "https://i.ibb.co.com/39dsXJMv/B2-Nada-dan-Melodinya-Page-07.jpg" },
      { text: "", image: "https://i.ibb.co.com/zW5Jz603/B2-Nada-dan-Melodinya-Page-08.jpg" },
      { text: "", image: "https://i.ibb.co.com/x88GbvF5/B2-Nada-dan-Melodinya-Page-09.jpg" },
      { text: "", image: "https://i.ibb.co.com/mVMvP4Qm/B2-Nada-dan-Melodinya-Page-10.jpg" },
      { text: "", image: "https://i.ibb.co.com/YTt8v8ty/B2-Nada-dan-Melodinya-Page-11.jpg" },
      { text: "", image: "https://i.ibb.co.com/ch4qRKV6/B2-Nada-dan-Melodinya-Page-12.jpg" },
      { text: "", image: "https://i.ibb.co.com/LDjSCy4Z/B2-Nada-dan-Melodinya-Page-13.jpg" }
    ]
  }
];
